### ISSUE TITLE
Sync services file with keylime source?

### ISSUE THREAD

**Issue by utkarsh2102** [keylime/keylime-deb#8]
Hello,

I see that keylime source ships `services/`, which has all 3 service files. However the ones here, inside `debian/`, are somewhat different, in the sense, that it adds a few more configuration entries which totally makes sense. 

So I'd rather like to know if they could instead be moved to the keylime source and simply symlinked here? Doing this would essentially save us from the need to worry about syncing changes if and whenever there's any. What do you think?

**Comment by galmasi** [comment]
There is the additional problem that there are service files for RPM as well. I tend to think that we probably want the debian-specific service file to stay in the debian package.

**Comment by galmasi** [comment]
Discussed this issue with @mpeters yesterday. The current agreement is to keep the systemd files specific to Ubuntu here in this package for now.

**Comment by utkarsh2102** [comment]
OK, that's fair enough! Thanks!
